baseURL: "https://CrownDestro.github.io"
languageCode: "en-us"
title: "My-Self"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hey, I am "
    title: "Dheeraj M."
    subtitle: "A Student and Enthusiast"
    content: "A passionate CSE student with a belief in the transformative power of technology and look forward to exploring, innovating, and building a brighter future. "
    image: /images/hal.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1Ow5wxKh50rd_58NPyaD8lEFZeObqNu29/view"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/CrownDestro/
        - icon: fab fa-instagram
          url: https://www.instagram.com/dheerajmotupalli/
      customIcons:
        - icon: /linkd.png
          url: "https://www.linkedin.com/in/dheeraj-motupalli-719a66287/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me1.jpg"
    content: |-
      First year student at Amrita Vishwa Vidyapeetham who is eager to learn new stuff.
    skills:
      enable: true
      title: "Below are some technologies I'm working on:"
      items:
        - "HTML"
        - "CSS"
        - "Python"
        - "JavaScript"
        - "SQL"

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "BTech CSE"
        school:
          name: "Amrita School of Computing"
          url: "https://www.amrita.edu/campus/amritapuri/"
        date: "2023 - 2027"
        GPA: "4.38 out of 5.0"
        content: |-
          Extracurricular Activities
            - I play Outdoor Sports.
            - A casual PC gamer.
      - title: "High School"
        school:
          name: "ParamJyoti International School"
          url: "https://www.paramjyotischools.in/"
        GPA: "9.1 out of 10.0"
        featuredLink:
          enable: true
          url: "https://www.facebook.com/paramjyotischool/photos/pb.100063915851088.-2207520000/217153462058733/?type=3"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://CrownDestro.github.io
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:motupallidheeraj@gmail.com
          - icon: fab fa-github
            url: https://github.com/CrownDestro

      - title: Merchandise Web
        content: A web app for the sale of the accessories of the famous music band Imagine Dragons.
        image: /images/projects/backdrop.png
        badges:
          - "HTML"
          - "CSS"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/CrownDestro/amfoss-tasks_S2/tree/main/task-05

      - title: Weather Forecast
        content: A clean and simple Interface where you the get today's weather info of any part of the world you wish.
        image: /images/projects/qwe.png
        badges:
          - "API"
          - "HTML"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/CrownDestro/amfoss-tasks_S2/tree/main/task-07

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:motupallidheeraj@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/CrownDestro
      linkedin: https://www.linkedin.com/in/dheeraj-motupalli-719a66287/
      twitter: https://twitter.com
      instagram: https://www.instagram.com/dheerajmotupalli/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
